-- ============================================================
-- 002_create_empresas.sql
-- Empresas do Estoque Flex
-- ============================================================

CREATE TABLE core.empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nome VARCHAR(160) NOT NULL,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_empresas_nome_nao_vazio
    CHECK (BTRIM(nome) <> '')
);