-- ============================================================
-- 003_create_unidades.sql
-- Unidades de medida do Estoque Flex
-- ============================================================

CREATE TABLE core.unidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    empresa_id BIGINT NOT NULL,

    nome VARCHAR(80) NOT NULL,

    simbolo VARCHAR(20),

    permite_decimal BOOLEAN NOT NULL DEFAULT TRUE,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_unidades_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES core.empresas(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_unidades_nome_nao_vazio
        CHECK (BTRIM(nome) <> ''),

    CONSTRAINT ck_unidades_simbolo_nao_vazio
        CHECK (
            simbolo IS NULL
            OR BTRIM(simbolo) <> ''
        ),

    CONSTRAINT uq_unidades_empresa_nome
        UNIQUE (empresa_id, nome),

    CONSTRAINT uq_unidades_empresa_id
        UNIQUE (empresa_id, id)
);

CREATE INDEX idx_unidades_empresa_ativo
    ON core.unidades (empresa_id, ativo);