-- ============================================================
-- 004_create_itens.sql
-- Itens controlados pelo Estoque Flex
-- ============================================================

CREATE TABLE core.itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    empresa_id BIGINT NOT NULL,

    unidade_id BIGINT NOT NULL,

    nome VARCHAR(160) NOT NULL,

    descricao TEXT,

    estoque_minimo NUMERIC(18,4) NOT NULL DEFAULT 0,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_itens_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES core.empresas(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_itens_unidade_empresa
        FOREIGN KEY (empresa_id, unidade_id)
        REFERENCES core.unidades(empresa_id, id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_itens_nome_nao_vazio
        CHECK (BTRIM(nome) <> ''),

    CONSTRAINT ck_itens_estoque_minimo_nao_negativo
        CHECK (estoque_minimo >= 0),

    CONSTRAINT uq_itens_empresa_nome
        UNIQUE (empresa_id, nome),

    CONSTRAINT uq_itens_empresa_id
        UNIQUE (empresa_id, id)
);

CREATE INDEX idx_itens_empresa_ativo
    ON core.itens (empresa_id, ativo);