-- ============================================================
-- 005_create_movimentacoes.sql
-- Histórico de movimentações de estoque
-- ============================================================

CREATE TABLE core.movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    empresa_id BIGINT NOT NULL,

    item_id BIGINT NOT NULL,

    tipo VARCHAR(30) NOT NULL,

    quantidade NUMERIC(18,4) NOT NULL,

    motivo VARCHAR(255),

    observacao TEXT,

    ocorrida_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_movimentacoes_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES core.empresas(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimentacoes_item_empresa
        FOREIGN KEY (empresa_id, item_id)
        REFERENCES core.itens(empresa_id, id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_movimentacoes_tipo
        CHECK (
            tipo IN (
                'ENTRADA',
                'SAIDA',
                'AJUSTE_ENTRADA',
                'AJUSTE_SAIDA'
            )
        ),

    CONSTRAINT ck_movimentacoes_quantidade_positiva
        CHECK (quantidade > 0),

    CONSTRAINT ck_movimentacoes_motivo_nao_vazio
        CHECK (
            motivo IS NULL
            OR BTRIM(motivo) <> ''
        )
);

CREATE INDEX idx_movimentacoes_item_ocorrida_em
    ON core.movimentacoes (item_id, ocorrida_em);

CREATE INDEX idx_movimentacoes_empresa_ocorrida_em
    ON core.movimentacoes (empresa_id, ocorrida_em);

-- ============================================================
-- PROTEGER UNIDADE DO ITEM APOS EXISTIREM MOVIMENTACOES
-- ============================================================

CREATE OR REPLACE FUNCTION core.fn_bloquear_troca_unidade_item()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

    IF OLD.unidade_id IS DISTINCT FROM NEW.unidade_id
       AND EXISTS (
            SELECT 1
            FROM core.movimentacoes
            WHERE item_id = OLD.id
              AND empresa_id = OLD.empresa_id
       )
    THEN
        RAISE EXCEPTION
            'Nao e permitido alterar a unidade de um item que possui movimentacoes.';
    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER trg_bloquear_troca_unidade_item
BEFORE UPDATE OF unidade_id
ON core.itens
FOR EACH ROW
EXECUTE FUNCTION core.fn_bloquear_troca_unidade_item();

-- ============================================================
-- PROTEGER HISTORICO DE MOVIMENTACOES
-- ============================================================

CREATE OR REPLACE FUNCTION core.fn_proteger_movimentacao_historica()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'Movimentacoes historicas nao podem ser alteradas ou excluidas. Registre um movimento compensatorio.';
END;
$$;

CREATE TRIGGER trg_proteger_movimentacao_historica
BEFORE UPDATE OR DELETE
ON core.movimentacoes
FOR EACH ROW
EXECUTE FUNCTION core.fn_proteger_movimentacao_historica();