-- ============================================================
-- 005_create_movimentacoes.sql
-- Histórico de movimentações de estoque
-- ============================================================

CREATE TABLE core.movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    empresa_id BIGINT NOT NULL,

    item_id BIGINT NOT NULL,

    tipo VARCHAR(30) NOT NULL,

    quantidade NUMERIC(18,4) NOT NULL,

    motivo VARCHAR(255),

    observacao TEXT,

    ocorrida_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_movimentacoes_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES core.empresas(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimentacoes_item_empresa
        FOREIGN KEY (empresa_id, item_id)
        REFERENCES core.itens(empresa_id, id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_movimentacoes_tipo
        CHECK (
            tipo IN (
                'ENTRADA',
                'SAIDA',
                'AJUSTE_ENTRADA',
                'AJUSTE_SAIDA'
            )
        ),

    CONSTRAINT ck_movimentacoes_quantidade_positiva
        CHECK (quantidade > 0),

    CONSTRAINT ck_movimentacoes_motivo_nao_vazio
        CHECK (
            motivo IS NULL
            OR BTRIM(motivo) <> ''
        )
);

CREATE INDEX idx_movimentacoes_item_ocorrida_em
    ON core.movimentacoes (item_id, ocorrida_em);

CREATE INDEX idx_movimentacoes_empresa_ocorrida_em
    ON core.movimentacoes (empresa_id, ocorrida_em);