-- ============================================================
-- 006_create_inventarios.sql
-- Inventários físicos do Estoque Flex
-- ============================================================

CREATE TABLE core.inventarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    empresa_id BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ABERTO',

    observacao TEXT,

    iniciado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    concluido_em TIMESTAMPTZ,

    cancelado_em TIMESTAMPTZ,

    CONSTRAINT fk_inventarios_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES core.empresas(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_inventarios_status
        CHECK (
            status IN (
                'ABERTO',
                'CONCLUIDO',
                'CANCELADO'
            )
        ),

    CONSTRAINT ck_inventarios_status_datas
        CHECK (
            (
                status = 'ABERTO'
                AND concluido_em IS NULL
                AND cancelado_em IS NULL
            )
            OR
            (
                status = 'CONCLUIDO'
                AND concluido_em IS NOT NULL
                AND cancelado_em IS NULL
            )
            OR
            (
                status = 'CANCELADO'
                AND cancelado_em IS NOT NULL
                AND concluido_em IS NULL
            )
        ),

    CONSTRAINT uq_inventarios_empresa_id
        UNIQUE (empresa_id, id)
);

CREATE INDEX idx_inventarios_empresa_status
    ON core.inventarios (empresa_id, status);

-- ============================================================
-- PROTEGER INVENTARIOS HISTORICOS
-- ============================================================

CREATE OR REPLACE FUNCTION core.fn_proteger_inventario_historico()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'Inventarios nao podem ser excluidos. Utilize o cancelamento.';
    END IF;

    IF OLD.status IN ('CONCLUIDO', 'CANCELADO') THEN
        RAISE EXCEPTION
            'Inventarios concluidos ou cancelados nao podem ser alterados.';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_proteger_inventario_historico
BEFORE UPDATE OR DELETE
ON core.inventarios
FOR EACH ROW
EXECUTE FUNCTION core.fn_proteger_inventario_historico();