CREATE TABLE custom.categorias (
    id BIGINIT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    empresa_id BIGINT NOT NULL,

    nome VARCHAR(120) NOT NULL,

    descricao TEXT,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    atualizado em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_categorias_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES core.empresas(id)
    ON DELETE RESTRICT

    CONSTRAINT uq_categorias_empresa_nome
    UNIQUE (empresa_id, nome)
);