CREATE TABLE custom.campos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    empresa_id BIGINT NOT NULL,

    categoria_id BIGINT NOT NULL,

    nome VARCHAR(120) NOT NULL,

    tipo_dado VARCHAR(30) NOT NULL,

    obrigatorio BOOLEAN NOT NULL DEFAULT FALSE,

    configuracao JSONB NOT NULL DEFAULT '{}'::jsonb,

    ordem_exibicao INTEGER NOT NULL DEFAULT 0,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_campos_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES core.empresas(id)
    ON DELETE RESTRICT,

    CONSTRAINT fk_campos_categoria
    FOREIGN KEY (categoria_id)
    REFERENCES custom.categorias(id)
    ON DELETE RESTRICT,

    CONSTRAINT ck_campos_tipo_dado
    CHECK (
        tipo_dado IN (
            'TEXTO_CURTO',
            'TEXTO_LONGO',
            'INTEIRO',
            'DECIMAL',
            'DINHEIRO',
            'BOOLEANO',
            'DATA',
            'LISTA'
        )
    ),

    CONSTRAINT uq_campos_categoria_nome
    UNIQUE (categoria_id, nome)
);