CREATE TABLE custom.campo_opcoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    campo_id BIGINT NOT NULL,

    valor VARCHAR(150) NOT NULL,

    ordem_exibicao INTEGER NOT NULL DEFAULT 0,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_campo_opcoes_campo
    FOREIGN KEY (campo_id)
    REFERENCES custom.campos(id)
    ON DELETE RESTRICT,

    CONSTRAINT uq_campo_opcoes_campo_valor
    UNIQUE (campo_id, valor)
);