CREATE TABLE custom.valores_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    item_id BIGINT NOT NULL,
    campo_id BIGINT NOT NULL,

    valor_texto TEXT,
    valor_inteiro BIGINT,
    valor_decimal NUMERIC(18,4),
    valor_monetario NUMERIC(18,2),
    valor_booleano BOOLEAN,
    valor_data DATE,
    opcao_id BIGINT,

    CONSTRAINT fk_valores_item_item
    FOREIGN KEY (item_id)
    REFERENCES core.itens(id)
    ON DELETE RESTRICT,

    CONSTRAINT fk_valores_item_campo
    FOREIGN KEY (campo_id)
    REFERENCES custom.campos(id)
    ON DELETE RESTRICT,

    CONSTRAINT fk_valores_item_opcao
    FOREIGN KEY (opcao_id)
    REFERENCES custom.campo_opcoes(id)
    ON DELETE RESTRICT,

    CONSTRAINT uq_valores_item_item_campo
    UNIQUE (item_id, campo_id),

    CONSTRAINT ck_valores_item_um_valor
    CHECK (
        num_nonnulls(
            valor_texto,
            valor_inteiro,
            valor_decimal,
            valor_monetario,
            valor_booleano,
            valor_data,
            opcao_id
        ) = 1
    )
);