-- ============================================================
-- 111_create_usuarios.sql
-- Usuários da aplicação
-- ============================================================

CREATE TABLE auth.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nome VARCHAR(120) NOT NULL,

    email VARCHAR(254) NOT NULL,

    senha_hash VARCHAR(255) NOT NULL,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_usuarios_nome_nao_vazio
    CHECK (BTRIM(nome) <> ''),

    CONSTRAINT ck_usuarios_email_nao_vazio
    CHECK (BTRIM(email) <> ''),

    CONSTRAINT ck_usuarios_senha_hash_nao_vazio
    CHECK (BTRIM(senha_hash) <> '')
);

CREATE UNIQUE INDEX uq_usuarios_email_lower
ON auth.usuarios (LOWER(email));